### ISSUE TITLE
'doc' not defined in plugin context

### ISSUE THREAD

**Issue by knekke** [gr4ph0s/C4D_RedshiftWrapper_API#2]
Hi,
thanks for the wrapper! I have a tiny problem when I try to include your wrapper into a plugin. As a standalone script everything runs fine, but in a plugin context I get:
`global name 'doc' is not defined` when I run rs.CreateMaterial()
I'm pretty new to c4d, so no idea why it makes a difference.

**Comment by gr4ph0s** [comment]
Thanks I will fix it later today. :)

**Comment by knekke** [comment]
btw what command did you run for the pyminifier? It seems the only way to include the imports is pyz, but that is not what you used...?

**Comment by gr4ph0s** [comment]
Fixed,
Do you need a minified version also?
About pyminifier, I do it manually by merging all files of the module within one python file and then I simply run pyminifer as default

**Comment by knekke** [comment]
All good, I have it working now.
I had to change line 255 in Redshift.py to:
if not isinstance(doc, c4d.documents.BaseDocument) and doc is not None:

Thanks!

**Comment by drewyeaton** [comment]
Hey guys, I've created a pull request for the suggested fix above: https://github.com/gr4ph0s/C4D_RedshiftWrapper_API/pull/3

Great work on this project!

**Comment by gr4ph0s** [comment]
Thanks a lot guys, I should have more personal time this year (at least this month I get more).

So I will try to update with the current rs state within the week (it's been a while since I looked to rs, stuff may have changed)
